[ClassVersion("1.0.0")]
Class RandomCimInstance
{
    [Write,ValueMap{"http", "https"},Values{"http", "https"}] string Protocol;
    [write]String IPAddress;
    [write]String HostName;

};


[ClassVersion("1.0.0"), FriendlyName("EmbeddedCIM")]
class EmbeddedCIM :  OMI_BaseResource
{
	[Key] string Name;
  [write, EmbeddedInstance("RandomCimInstance")] string InstanceArray[];
};



