---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero

verifier:
  name: pester

platforms:
  - name: windows-2012r2-chef12
    driver:
      box: chef/windows-server-2012r2-standard

suites:
  - name: hashes
    run_list:
      - recipe[dsc_testing::with_hashes]
  - name: hashes
    run_list:
      - recipe[dsc_testing::reboot_pending]
