---
driver:
  name: vagrant
  linked_clones: true
  gui: false
  communicator: winrm
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

verifier:
  name: pester

platforms:
  - name: windows-2012r2-wmf5-chef12
    driver:
      box: smurawski/2012R2-wmf5
suites:
  - name: pullserver
    run_list:
      - recipe[dsc_testing::test_pull_server]
  - name: partials
    run_list:
      - recipe[dsc_testing::test_partials]
  - name: packagemanagement
    run_list:
      - recipe[dsc_testing::test_package_mgmt]
  - name: credentials
    run_list:
      - recipe[dsc_testing::credentials]
  - name: hashes
    run_list:
      - recipe[dsc_testing::with_hashes]
  - name: reboot_pending
    run_list:
      - recipe[dsc_testing::reboot_pending]
  - name: embedded_cim_instance
    run_list:
      - recipe[dsc_testing::embedded_cim_instance]
  - name: errors
    run_list:
      - recipe[dsc_testing::errors]
  - name: resources_in_dsc_script
    run_list:
      - recipe[dsc_testing::resources_in_dsc_script]